spring:
  application:
    name: PRODUCT_SERVICE
  datasource:
    password: 123456
    username: postgres
    url: jdbc:postgresql://localhost:5432/ecommerce
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082